const chatbotToggler = document.querySelector(".chatbot-toggler");
const closeBtn = document.querySelector(".close-btn");
const chatbox = document.querySelector(".chatbox");
const chatInput = document.querySelector(".chat-input textarea");
const sendChatBtn = document.querySelector(".chat-input span");

let userMessage = null; // Variable to store user's message

const inputInitHeight = chatInput.scrollHeight;

const createChatLi = (message, className) => {
  // Create a chat <li> element with passed message and className
  const chatLi = document.createElement("li");
  chatLi.classList.add("chat", `${className}`);
  let chatContent = className === "outgoing" ? `<p></p>` : `<span class="material-symbols-outlined">smart_toy</span><p></p>`;
  chatLi.innerHTML = chatContent;
  chatLi.querySelector("p").textContent = message;
  return chatLi; // return chat <li> element
};

const predefinedResponses = {
  hello: "Hi there! How can I help you today?",
  "how are you": "I'm doing well, thanks for asking! How about you?",
  hii: "Hi there! How can I help you today?",
  "education schemes":
    "1:Sarva shiksna abhiyan(SSA)\n2:Rashtriya Madhyamik Shiksha Abhiyan (RMSA)\n3: Mid-Day Meal Scheme,\n4: Beti Bachao Beti Padhao (BBBP),\n5: Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
  ssa: "Sarva Shiksha Abhiyan (SSA): This scheme aims to provide universal elementary education by ensuring the availability of quality education at the primary and upper primary level (from Class I to Class VIII) for all children of the country in the age group of 6-14 years: (https://www.aicte-india.org/reports/overview/Sarva-Shiksha-Abhiyan)",
  mdm: "Mid-Day Meal Scheme: This scheme provides free lunch on all working days to children studying in Class I to VIII in government, government-aided schools, and local body schools. The scheme aims to improve nutritional levels among children belonging to disadvantaged sections and increase enrolment and attendance in schools.",
  BBBP: "Beti Bachao Beti Padhao (BBBP): This initiative aims to address the issue of declining Child Sex Ratio (CSR) and empower girls. It focuses on creating awareness and improving the implementation of existing schemes for girls' education.",
  social: "https://www.aicte-india.org/reports/overview/Sarva-Shiksha-Abhiyan",
  bye: "Goodbye! Have a great day!",
  rmsa: "Rashtriya Madhyamik Shiksha Abhiyan (RMSA): Launched in 2009, the Rashtriya Madhyamik Shiksha Abhiyan (RMSA) aims to improve the quality of education at the secondary level (from Class IX to Class XII) and enhance access for all children irrespective of their caste, religion, or gender.",
  pmkvy :"Pradhan Mantri Kaushal Vikas Yojana (PMKVY): This initiative aims to provide market-relevant skill training to youth who are looking for new-age industry jobs. It offers a bouquet of courses to cater to the needs of various sectors of the economy.",
  bbbp:"Beti Bachao Beti Padhao (BBBP): This initiative aims to address the issue of declining Child Sex Ratio (CSR) and empower girls. It focuses on creating awareness and improving the implementation of existing schemes for girls' education.",
  healthcare:"1:Janani Shishu Suraksha Karyakaram (JSSK)\n2:Rashtriya Kishor Swasthya Karyakram(RKSK)\n3:Rashtriya Bal Swasthya Karyakram (RBSK)\n4:Universal Immunisation Programme\n5:Mission Indradhanush (MI)\n6:Janani Suraksha Yojana (JSY)\n7:Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)\n8:Navjaat Shishu Suraksha Karyakram (NSSK)\n9:National Programme for Family planning",
  healthcareschemes:"1:Janani Shishu Suraksha Karyakaram (JSSK)\n2:Rashtriya Kishor Swasthya Karyakram(RKSK)\n3:Rashtriya Bal Swasthya Karyakram (RBSK)\n4:Universal Immunisation Programme\n5:Mission Indradhanush (MI)\n6:Janani Suraksha Yojana (JSY)\n7:Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)\n8:Navjaat Shishu Suraksha Karyakram (NSSK)\n9:National Programme for Family planning",
  welfare :" 1:Dr. Muthulakshmi Reddy Ninaivu Inter-Caste Marriage Assistance Scheme\n2:Dr. Dhaarmalammal Ammaiyar Ninaivu Widow Remarriage Assistance Scheme\n3:E.V.R. Maniammalaiyar Ninaivu Marriage Assistance Scheme for Daughters of Poor Widows\n4:Annai Theresa Ninaivu Marriage Assistance Scheme for Orphan Girls\n5:Free housing schemes\n6:Pension schemes\n7:child adoption scheme\n8:Chief Minister's Girl Child Protection Scheme\n9:Moovalur Ramamirtham Ammaiyar Ninaivu Marriage Assistance Scheme\n10:Sathya Ammaiyar Ninaivu Government Chi",
  welfare :" 1:Dr. Muthulakshmi Reddy Ninaivu Inter-Caste Marriage Assistance Scheme\n2:Dr. Dhaarmalammal Ammaiyar Ninaivu Widow Remarriage Assistance Scheme\n3:E.V.R. Maniammalaiyar Ninaivu Marriage Assistance Scheme for Daughters of Poor Widows\n4:Annai Theresa Ninaivu Marriage Assistance Scheme for Orphan Girls\n5:Free housing schemes\n6:Pension schemes\n7:child adoption scheme\n8:Chief Minister's Girl Child Protection Scheme\n9:Moovalur Ramamirtham Ammaiyar Ninaivu Marriage Assistance Scheme\n10:Sathya Ammaiyar Ninaivu Government Chi",
  rural:"1:Tamil Nadu Village Habitation Improvement (THAI) Scheme\n2:Rural Infrastructure Scheme (RIS),\n3:National Bank for Agriculture and Rural Development (NABARD) RIDF\n4:Tamil Nadu Rural Roads Improvement Scheme (TNRRIS)",
  urban:"1:Integrated Urban Development Mission (IUDM)\n2:Tamil Nadu Urban Road Infrastructure Development Programme (TURIDP)\n3:Tamil Nadu Urban Development Fund (TNUDF)",
  environment:"1:Tamil Nadu State Environment Policy (TSEP)\n2:Environment Protection and Renewable Energy Development Fund(EPRED)\n3:National Lake Conservation Programme (NLCP)\n4:Tamil Nadu Biodiversity Conservation and Greening Project (TBGP)\n5:Wetlands conservation",
  cultural:"1:Tamil Nadu Maintenance and Development of Museums Scheme(TMDMS)\n2:Scheme for Financial Assistance to Historical Places(SFAHP)\n3:Development of Arts and Culture Scheme(DACS)\n4:Establishment of Heritage Towns(EHT)\n5:Arts and Crafts Village Complex Scheme(ACVCS)",
  security: "1:Military Alliances\n2:Border Security\n3:Cybersecurity\n4:Counterterrorism\n5:Intelligence Gathering\n6:Diplomacy\n7:Arms Control\n8:Disaster Preparedness and Response\n9:Peacekeeping Operations\n10:Defense Spending",
  technology: "1:Research and Development Grants\n2:Startup Incubator Programs\n3:Technology Transfer Offices\n4:Innovation Challenges\n5:Tech Parks and Innovation Hubs\n6:Public-Private Partnerships for Innovation\n7:Technology Adoption Grants\n8:Technology Accelerator Programs\n9:Open Innovation Platforms\n10:Technology Demonstration Projects",
  tell_some_schemes : "MALE (OR) FEMALE",
  tell_some_scheme: "MALE (OR) FEMALE",
  tell_schemes: "MALE (OR) FEMALE",
  schemes: "MALE (OR) FEMALE",
  scheme: "MALE (OR) FEMALE",
  government_schemes:"MALE (OR) FEMALE",
  government_scheme:"MALE (OR) FEMALE",
  what_are_the_schemes_in_tamilnadu:"MALE (OR) FEMALE",
  infrastructure_schemes:"Rural Infrastructure (Or) Urban Infrastructure",
  infrastructure_scheme:"Rural Infrastructure (Or) Urban Infrastructure",
  male :"1: Education Schemes\n2: Healthcare Schemes\n3: Social Welfare Schemes\n4: Rural Schemes\n5: Urban Development Schemes\n6: Environmental and Conservation Schemes\n7: Security and Defense Schemes\n8: Technology and Innovation Schemes\n9: Cultural and Heritage Schemes",
  female :"1: Education Schemes\n2: Healthcare Schemes\n3: Social Welfare Schemes\n4: Rural Schemes\n5: Urban Development Schemes\n6: Environmental and Conservation Schemes\n7: Security and Defense Schemes\n8: Technology and Innovation Schemes\n9: Cultural and Heritage Schemes",
  education:"school student or college student",
  school:"Samacheer Kalvi : This program ensures a uniform curriculum across all government, aided, and private schools in Tamil Nadu. This promotes equal educational opportunities and reduces disparities\nMidday Meal Scheme : This nationwide program provides free and nutritious lunch to students in government and government-aided schools from Class 1 to 12. It aims to improve their nutritional status and encourage school attendance.Free Textbooks : The government provides free textbooks to students in government and government-aided schools, reducing the financial burden on families.Kalaignar Karunanidhi Nutritious Meal Scheme (State-specific) : This scheme builds upon the Midday Meal Scheme by providing additional nutritional benefits to students in Tamil Nadu.Sarva Shiksha Abhiyan (SSA) : This centrally sponsored scheme focuses on universal elementary education by providing infrastructure and support for schools.Rashtriya Madhyamik Shiksha Abhiyan (RMSA) : This scheme focuses on improving the quality of education at the secondary level (from Class 8 to 12) by providing support for infrastructure, teacher training, and vocational education.Schemes for Meritorious Students Laptop Scheme : Meritorious students from underprivileged families receive free laptops to aid their higher education.District Level Prizes : Cash awards are given to students who excel in public examinations like Class 10 and 12 board exams to recognize and motivate them.Additionally School-specific schemes : Some schools may offer their own scholarships or financial aid programs for deserving students.Finding More Information For the latest information on all educational schemes, visit the official Tamil Nadu government portal [tn.gov.in]. The website allows you to explore schemes by department, making it easier to find those most relevant to your needs.You can also check the website of the Directorate of School Education, Tamil Nadu (https://tnschools.gov.in/) for updates on school-related schemes.Remember, this is not an exhaustive list. Its always best to consult official sources for the most current information.",
  college:"College students in Tamil Nadu can benefit from a variety of schemes offered by both the central and state governments. Here's a breakdown of some key categories:\n*Financial Assistance Schemes *\nFree Education for Girls (Periyar EVR Nagammai Free Education Scheme): This scheme provides financial aid by waiving tuition fees for women students from all communities pursuing undergraduate courses in government and aided colleges, subject to certain income limits [tn.gov.in].Merit-based Scholarships: Several scholarships are available for college students based on academic merit. Here are some examples:/n /n - BC, MBC & Minorities Welfare Department Scholarships: Offered to students belonging to Backward Classes, Most Backward Classes, and Minority communities [tn.gov.in].Government of Tamil Nadu Scholarship to BC/MBC/DNC Students pursuing UG/PG courses: Reimburses tuition fees and other mandatory fees for students from these communities studying in IITs, IIMs, NITs and other Central Universities [scholarship.iiitk.ac.in].University-specific scholarships: Many universities offer their own merit-based scholarships to undergraduate and postgraduate students.Post-matriculation Scholarships: SC, ST, MBC, and other designated communities can avail financial assistance to pursue undergraduate and postgraduate studies after Class 10 [tn.gov.in].Book Banks: Scheme provides libraries with reference books for students pursuing professional courses like engineering, medicine, and law [tn.gov.in].Coaching for Competitive Exams: Free coaching is offered exclusively for women students preparing for IAS/IPS exams at two government centers [tn.gov.in].Important Note: Eligibility criteria and application processes for these schemes can change. Always refer to the official government websites or college financial aid offices for the most up-to-date information.Here are some additional resources to help you find relevant schemes: Directorate of College Education, Tamil Nadu: https://www.tndce.tn.gov.in/ Websites of individual colleges and universities you're interested in Remember, exploring these resources can help you identify schemes that best suit your needs and background.",
  jssk:"The Janani Shishu Suraksha Karyakaram (JSSK) is a centrally sponsored scheme launched by the Government of India in June 2011 to provide free and quality healthcare to pregnant women and newborns. The scheme aims to reduce maternal and infant mortality rates in India by encouraging institutional deliveries and providing free and comprehensive care to mothers and newborns at government health facilities.Key Features of the JSSK Scheme:Free and cashless delivery, including caesarean section: All pregnant women delivering in government health facilities are entitled to free and cashless delivery, including caesarean section. This includes free drugs, consumables, diagnostics, blood, diet, and transport from home to health facility and back.Free essential newborn care: Sick newborns up to 30 days of age are entitled to free essential newborn care at government health facilities. This includes free drugs, consumables, diagnostics, blood, and treatment.Benefits of the JSSK Scheme:Reduced maternal and infant mortality rates: The JSSK scheme has been instrumental in reducing maternal and infant mortality rates in India. Institutional deliveries have increased significantly since the launch of the scheme, and this has led to a decline in the number of deaths of mothers and newborns.Improved access to quality healthcare: The JSSK scheme has made quality healthcare more accessible to pregnant women and newborns, especially in rural areas. The scheme has encouraged women to deliver in government health facilities, where they can receive free and comprehensive care.  Eligibility for the JSSK Scheme:All pregnant women and sick newborns up to 30 days of age are eligible for the benefits of the JSSK scheme. There is no requirement for BPL cards or any other documentation.How to Avail the Benefits of the JSSK Scheme:To avail the benefits of the JSSK scheme, pregnant women should simply go to any government health facility for delivery. In the case of sick newborns, parents should take them to the nearest government health facility for treatment.The JSSK scheme is a major step towards achieving the goal of universal health coverage in India. The scheme has made a significant impact on the lives of pregnant women and newborns, and it is continuing to play an important role in improving maternal and child health in India.Here are some additional resources for information on the JSSK scheme:https://nhm.assam.gov.in/schemes/janani-suraksha-yojana",
  rksk:"The Rashtriya Kishor Swasthya Karyakram (RKSK), launched in 2014, is an adolescent health program by the Ministry of Health and Family Welfare. It aims to improve the overall health and well-being of adolescents in India, aged 10 to 19 years. Here's a breakdown of the scheme's key features:Focus Areas:Nutrition: The program addresses nutritional deficiencies through weekly Iron Folic Acid (IFA) supplementation and biannual de-worming tablets for adolescents.Reproductive Health: RKSK promotes awareness about sexual and reproductive health and provides counseling services.Mental Health: The scheme acknowledges the importance of mental health and offers support mechanisms to address concerns.Key Strengths:Holistic Approach: RKSK goes beyond just physical health to encompass the mental and emotional well-being of adolescents.Adolescent Participation: The program encourages adolescent participation in promoting health awareness amongst their peers.Focus on Equity: RKSK ensures special focus on marginalized and underserved groups to bridge health equity gaps.Here are some resources for further reading on the RKSK scheme: Official RKSK website: https://nhm.gov.in/showlink.php?id=180",
  rbsk:"The Rashtriya Bal Swasthya Karyakram (RBSK), launched under the National Health Mission (NHM), is an initiative specifically designed for child health in India. It focuses on early identification and intervention for various health concerns in children aged 0 to 18 years. Here's a breakdown of the program:  Target Age Group:RBSK prioritizes children from birth to 18 years, categorized into two main groups:-0-6 years: This age group is managed primarily at District Early Intervention Centers (DEICs).-6-18 years: Children in this age group are addressed through existing public health facilities, while DEICs act as referral points if needed.  Key Features:  Early Detection: RBSK prioritizes early identification of health concerns to ensure timely intervention and improve treatment outcomes.Free Screening and Follow-up: The program offers free health checkups and screenings for children. Additionally, children diagnosed with conditions receive free treatment and follow-up care, including surgeries at higher-level healthcare facilities when necessary.Benefits:Improved child health outcomes through early detection and intervention.Reduced morbidity and mortality rates in children.Enhanced access to comprehensive healthcare services for children across all age groups.Overall, the Rashtriya Bal Swasthya Karyakram (RBSK) is a crucial program for safeguarding the health and well-being of children in India. By focusing on early identification and intervention, it strives to create a healthier generation of children.Here are some resources for further reading on the RBSK scheme:Official RBSK website: https://rbsk.mohfw.gov.in/",
  mi:"Launched in December 2014, Mission Indradhanush is a special initiative under India's Universal Immunization Programme (UIP). It aims to achieve high levels of full immunization coverage (90% or more) among children under two years of age and pregnant women.Key features of Mission Indradhanush:Focus on Low Coverage Areas: The program prioritizes districts with low immunization rates, aiming to reach every child and pregnant woman who might have missed out on routine vaccinationsIntensified Immunization Drives: Mission Indradhanush conducts special immunization drives to cover unvaccinated or partially vaccinated children and pregnant women. These drives involve reaching out to communities and ensuring accessibility of vaccinesBenefits of Mission Indradhanush:Reduced Vaccine-Preventable Diseases: By increasing immunization coverage, Mission Indradhanush helps protect children from life-threatening illnesses like diphtheria, measles, polio, and others.Improved Child Health Outcomes: Immunization is crucial for a child's overall health and development. This program contributes to a healthier childhood for millions of children in India.Current Status:Mission Indradhanush has evolved into a series of phases, with the latest being Intensified Mission Indradhanush (IMI). As of October 2023 (IMI 5.0), the program has achieved significant progress in immunizing children and pregnant women. However, efforts continue to ensure full immunization coverage across the country.Here are some resources for further reading on Mission Indradhanush: National Health Mission (NHM) on Mission Indradhanush: https://main.mohfw.gov.in/",
  intercastemarriage:"The Dr. Muthulakshmi Reddy Ninaivu Inter-Caste Marriage Assistance Scheme is a social welfare scheme launched by the Government of Tamil Nadu to encourage inter-caste marriages and promote social harmony. The scheme provides financial assistance to couples who have entered into inter-caste marriages.\n \n Eligibility:\n \n - Both the bride and groom should belong to different castes.\n \n -The bride should have passed the 10th standard and should be above 18 years of age at the time of marriage.\n \n -The annual income of the family should not exceed Rs. 1 lakh.\n \n Benefits:\n \n - Couples receive ₹25,000 along with a 1 Sovereign (8gm) 22-carat gold coin for making Thirumangalyam.\n \n - Graduate couples receive a sum of Rs.50,000/- along with 8gm Gold Coin.\n \n How to Apply:\n \n - Couples can apply for the scheme within one year from the date of their marriage.\n \n - The application form can be obtained from the office of the District Social Welfare Officer.\n \n - The application form should be submitted along with the required documents, including the marriage certificate, caste certificate, income certificate, and educational qualification certificate.\n \n For more information, you can visit the website of the Department of Social Welfare and Women Empowerment, Government of Tamil Nadu: https://www.tn.gov.in/scheme/data_view/3470",
  ninaivuwidow:"The Dr. Dhaarmalammal Ammaiyar Ninaivu Widow Remarriage Assistance Scheme is a social welfare initiative launched by the Government of Tamil Nadu to encourage widow remarriage and support the rehabilitation of widows. The scheme provides financial assistance to widows who choose to remarry.\n \n Eligibility:\n \n - The widow should be a permanent resident of Tamil Nadu.\n \n - She should not have remarried earlier.\n \n - Her age should not be more than 60 years at the time of remarriage.\n \n - The annual income of the widow's family should not exceed Rs. 1 lakh.\n \n Benefits:\n \n - Widows receive financial assistance of ₹15,000 through ECS and ₹10,000 as National Savings Certificate along with a 4 gram 22 carat gold coin for making Thirumangalyam.\n \n - If the widow is a graduate or diploma holder, she receives ₹50,000, out of which ₹30,000 is given through ECS and ₹20,000 is given as National Savings Certificate along with a 4 gram 22 carat gold coin for making Thirumangalyam.\n \n How to Apply:\n \n - Widows can apply for the scheme within one year from the date of their remarriage.\n \n - The application form can be obtained from the office of the District Social Welfare Officer.\n \n - The application form should be submitted along with the required documents, including the marriage certificate, widow certificate, income certificate, and educational qualification certificate (if applicable).\n \n - For more information, you can visit the website of the Department of Social Welfare and Women Empowerment, Government of Tamil Nadu: https://www.tn.gov.in/scheme/data_view/3468",
  ninaivumarriageassistance :"The E.V.R. Maniammalaiyar Ninaivu Marriage Assistance Scheme for Daughters of Poor Widows is a financial aid program by the Government of Tamil Nadu to support poor widows in marrying off their daughters. Here's a breakdown of the scheme's key details:\n \n Eligibility:\n \n The bride's mother should be a widow.\n \n The bride should have passed the 10th standard (or 5th standard for Scheduled Tribe communities).\n \n There might be an annual income limit for the family (information not readily available online).\n \n Benefits:\n \n The scheme provides financial assistance of ₹50,000 to the bride's family.\n \n Additionally, they receive one Sovereign (8 grams) of 22-carat gold coin specifically meant for making the Thirumangalyam (sacred thread worn by married women).\n \n Application Process:\n \n Specific details about the application process are not available online. It's likely that applications are submitted through the District Social Welfare Officer's office.\n \n Recommendations:\n \n To get the most recent information and application procedures, it's advisable to visit the website of the Department of Social Welfare and Women Empowerment, Government of Tamil Nadu https://tnsocialwelfare.tn.gov.in/en.",
  orphangirls:"The Annai Theresa Ninaivu Marriage Assistance Scheme for Orphan Girls is a financial assistance program implemented by the Government of Tamil Nadu to support orphan girls during their marriage. Here's a breakdown of the key details:\n \n Eligibility:\n \n - Orphan Girl (Both parents deceased) residing in Tamil Nadu.\n \n - No minimum educational qualification required (though some sources mention 10th standard passed as a criterion, it's best to confirm with official sources).\n \n - Bride's age should be 18 years or above at the time of marriage.\n \n - The Groom's age should be 21 years or above at the time of marriage.\n \n - Income limit for the beneficiary is not a strict criterion as per most sources.\n \n  Benefits:\n \n - Financial assistance of ₹25,000 provided electronically through Electronic Clearing Service (ECS).\n \n - One Sovereign (8 grams) of 22-carat gold coin specifically meant for making the Thirumangalyam (sacred thread worn by married women).\n \n  Application Process:\n \n - Applications are typically submitted well in advance of the wedding (ideally 40 days before the marriage date).\n \n - The application form can likely be obtained from the District Social Welfare Officer's office in your district.\n \n - The application form needs to be submitted along with necessary documents like death certificates of parents (or orphan certificate), income certificate (if required), marriage invitation card, age proof of the bride, bride's photograph, and bills towards purchase of marriage articles (up to a specific amount).\n \n  Resources for More Information:\n \n - While an official government website for the scheme might not be readily available, here are some resources that provide details about the program:\n https://www.myscheme.gov.in/schemes/atnmasfogi",
  thai:"The Tamil Nadu Village Habitation Improvement (THAI) Scheme is a flagship program launched by the Government of Tamil Nadu in 2011-12. It addresses the uneven distribution of resources in rural areas by providing basic infrastructure facilities to all habitations. Tamil Nadu is the only state in India that focuses on habitation as the unit of development for such a scheme.\n \n Objectives of THAI Scheme\n \n - Improve basic amenities in rural areas\n \n - Bridge the gap in infrastructure development across villages\n \n - Ensure all habitations have access to essential services\n \n Components of THAI Scheme\n \n The THAI Scheme focuses on various aspects of rural infrastructure development, including:\n \n - Water Supply:Providing clean drinking water through pipelines and standpipes\n \n - Street Lights:Installing street lights for improved visibility and safety at night\n \n - Roads and Drainage:Constructing and improving roads for better connectivity and drainage systems for proper sanitation\n \n - Solid Waste Management: Creating proper disposal mechanisms for solid waste\n \n - Burial Grounds: Developing and improving burial grounds\n \n - Community Centers: Constructing community centers for social gatherings and events\n \n - Public Libraries: Establishing libraries to promote education and literacy\n \n - Playgrounds: Creating playgrounds for children \n \n Impact of THAI Scheme\n \n The THAI Scheme has played a significant role in improving the quality of life in rural Tamil Nadu. It has led to:\n \n - Improved access to basic amenities like clean water, sanitation, and proper roads\n \n - Enhanced safety and security in villages with better street lighting\n \n - Increased social interaction and community development through community centers and playgrounds\n \n -  Improved educational opportunities through libraries\n \n The THAI Scheme is an ongoing initiative, and the government continues to allocate funds for its implementation in various villages across the state.",
  ris:"The Rural Infrastructure Scheme (RIS) is a program implemented by the Government of Tamil Nadu, India, that aims to improve basic infrastructure facilities in rural areas, particularly the road network.\n \n The scheme focuses on stabilizing the assets created under the Mahatma Gandhi National Rural Employment Guarantee Scheme (MGNREGS) and maintaining these facilities. MGNREGS is a national program that provides guaranteed wage employment to adults in rural areas of India.\n \n Here are the specific objectives of the Rural Infrastructure Scheme:\n \n - Upgradation of existing earthen and gravel roads into weather-beaten (WBM) roads.\n \n - Upgradation of existing WBM roads into blacktopped (BT) roads.\n \n - Repairs to sluices, surplus weirs, and construction of retaining walls in water bodies desilted under MGNREGS.\n \n - Construction of culverts and retaining walls in newly formed roads under MGNREGS.\n \n By improving rural infrastructure, the RIS aims to:\n \n - Enhance rural connectivity\n \n - Boost economic development in rural areas\n \n - Improve the overall quality of life for people living in rural communities\n \n The RIS is an important program that is helping to bridge the gap in infrastructure between rural and urban areas in Tamil Nadu.",
  nabard:"The National Bank for Agriculture and Rural Development (NABARD) is an All India Financial Institution (AIFI) and an apex regulatory body for overall supervision of Regional Rural Banks, State Cooperative Banks and District Central Cooperative Banks in India/n /n NABARD serves as an apex financing agency for the institutions providing investment and production credit for promoting the various developmental activities in rural areas. It co-ordinates the rural financing activities of all institutions engaged in developmental work at the field level and maintains liaison with the Government of India, state governments, Reserve Bank of India (RBI) and other national level institutions concerned with policy formulation./n /n Here are some of the key functions of NABARD:/n /n - Provides financial assistance to state governments, Scheduled Commercial Banks (SCBs), State Cooperative Banks (SCBs), Regional Rural Banks (RRBs) etc., for promoting rural development./n /n - Regulates the functioning of institutions like RRBs, SCBs, and Central Cooperative Banks (CCBs)./n /n - Conducts research on issues related to rural development and agriculture./n /n - Provides refinance to financial institutions against their loans to agriculture and rural sector./n /n - Issues bonds to raise funds for rural development./n /n - Promotes financial inclusion by supporting Self-Help Groups (SHGs) and microfinance institutions./n /n Overall, NABARD plays a crucial role in supporting rural development in India by providing financial assistance, promoting financial inclusion, and undertaking research and development activities.",
  tnrris:"The Tamil Nadu Rural Roads Improvement Scheme (TNRRIS) is a program launched by the Government of Tamil Nadu in 2015-16 to specifically address the improvement of rural roads in the state. Here's a breakdown of TNRRIS:\n \n Objectives:\n \n Ensure optimal allocation of funds for three key areas:\n \n - Upgradation of existing roads\n \n - Strengthening of damaged roads\n \n - Maintenance of existing roads\n \n Focus:\n \n - Panchayat Union and Village Panchayat roads - These are roads that connect villages and are under the jurisdiction of local governing bodies.\n \n Funding:\n \n - Primarily funded by State Finance Commission Grants devolved for rural local bodies.\n \n - Initial allocation - Rs. 800 crore\n \n Benefits:\n \n - Improved rural connectivity\n \n - Enhanced economic activity in rural areas\n \n - Better access to markets, education, and healthcare facilities\n \n - Improved quality of life for rural communities\n \n Overall, TNRRIS plays a vital role in bridging the infrastructure gap between rural and urban areas in Tamil Nadu.\n \n Additional Points:\n \n - You can find more information on the official website of the Department of Rural Development & Panchayat Raj, Tamil Nadu government, but it may not have the latest updates https://www.tnrd.tn.gov.in/.",
  iudm:"The Integrated Urban Development Mission (IUDM) is a state-run program implemented by the Government of Tamil Nadu, India. It focuses on improving essential infrastructure facilities in urban areas, excluding Chennai, the capital city.\n \n Here's a breakdown of IUDM:\n \n Functioning Periods:\n \n - Initial Phase: 2011-12 to 2015-16 (5 years)\n \n - Relaunch: 2018-19 onwards (ongoing)\n \n Goal: Upgrade basic infrastructure in cities and towns.\n \n Target Areas: Corporations (except Chennai), Municipalities, and Town Panchayats.\n \n Types of Infrastructure Addressed:\n \n - Roads\n \n - Drinking water supply\n \n - Street lighting\n \n - Sewerage systems\n \n - Storm water drains\n \n - Sanitation facilities\n \n - Solid waste management\n \n - Bus stands\n \n - Parks\n \n Key Points:\n \n - IUDM has funded over 13,257 projects in its initial phase with a total investment of Rs. 9594.83 Crore.\n \n - As of September 2019, after the relaunch, over 549 projects were sanctioned with a cost of Rs. 1234 Crore.\n \n - The program is credited with enhancing the quality of life in urban areas of Tamil Nadu by improving basic necessities.\n \n Resources:\n \n - You can find more details on the official website of Tamil Nadu Urban Finance and Infrastructure Development Corporation Limited (TUFIDCO) - IUDM TUFIDCO: tufidco.in/iudm.aspx",
  turidp:"The Tamil Nadu Urban Road Infrastructure Development Programme (TURIDP) is a state-run initiative launched by the Government of Tamil Nadu, India, to specifically improve road infrastructure in urban areas. Here's what I can tell you about TURIDP:\n \n Objectives:\n \n - Upgrade and develop urban roads to enhance traffic flow and connectivity within cities and towns.\n \n Target Areas:\n \n - Corporations (except Chennai, the capital city)\n \n - Municipalities\n \n - Town Panchayats\n \n Types of Roads Addressed: \n \n - Major roads within urban areas\n \n - City and town roads requiring improvement\n \n Funding:\n \n - Primarily funded by the Tamil Nadu Urban Finance and Infrastructure Development Corporation (TUFIDCO).\n \n - Additional sources may include grants from the central government or loans from external agencies.\n \n Implementation:\n \n - Specific details on the implementing agency and project selection process are unavailable publicly.\n \n Expected Outcomes:\n \n - Improved traffic flow and reduced congestion in urban areas\n \n - Enhanced economic activity and development\n \n - Easier access to public transportation and other amenities\n \n Finding More Information:\n \n -  Unfortunately, there isn't readily available information on a dedicated government website for TURIDP.\n \n - You can try searching the websites of TUFIDCO (http://tufidco.in/) or the Department of Municipal Administration, Housing and Urban Development (TNHUD) (https://www.tn.gov.in/department/15) for updates or project details.",
  tnudf:"The Tamil Nadu Urban Development Fund (TNUDF) is a public-private partnership established by the Government of Tamil Nadu to address urban infrastructure needs in the state. Here's a breakdown of key points about TNUDF \n \n Origin and Purpose:\n \n - Established in November 1996 as a Trust under the Indian Trust Act, 1882.\n \n - Aimed at financing the implementation of urban infrastructure projects within Tamil Nadu.\n \n - Grew out of the Municipal Urban Development Fund (MUDF).\n \n Partnership Structure:\n \n - Public Partner: Government of Tamil Nadu \n \n - Private Partners: Leading financial institutions like ICICI Bank, Housing Development Finance Corporation (HDFC), and Infrastructure Leasing & Financial Services (IL&FS).\n \n Uniqueness:\n \n - TNUDF is considered the first public-private partnership in India to provide long-term debt financing for civic infrastructure projects without government guarantees.\n \n Management:\n \n - A Corporate Trustee, Tamil Nadu Urban Infrastructure Trustee Company Limited (TNUITCL), manages TNUDF.\n \n - The Board of Trustees periodically reviews lending policies and procedures.\n \n Funding Sources:\n \n - TNUDF doesn't solely rely on government funds.\n \n - It leverages external sources like the World Bank, KfW (German Development Bank), Japan International Cooperation Agency (JICA), and the Asian Development Bank (ADB).\n \n Focus Areas:\n \n While specific details might not be publicly available, TNUDF likely prioritizes projects that:\n \n - Improve essential services like water supply, sanitation, and waste management.\n \n - Enhance urban mobility through better roads and public transport infrastructure.\n \n - Promote environmental sustainability in urban development.\n \n Additional Resources:\n \n - While there isn't a dedicated website for TNUDF, you can find information on the website of Tamil Nadu Urban Infrastructure Financial Services Limited (TNUIFSL), which acts as the implementing agency for TNUDF: http://www.tnuifsl.com/",
  tsep:"The Tamil Nadu State Environment Policy 2017 isn't a single scheme, but a comprehensive policy document outlining the state's environmental goals and strategies. It serves as a roadmap for various initiatives aimed at protecting the environment and promoting sustainable development.\n \n Here are some key areas addressed by the Tamil Nadu State Environment Policy 2017:\n \n - Natural Resource Conservation: The policy emphasizes protecting natural resources like water, forests, and soil. This includes promoting water conservation practices, sustainable forest management, and preventing soil degradation.\n \n - Environmental Integration in Development Projects: The policy encourages integrating environmental considerations into development planning to minimize negative impacts and ensure ecologically friendly practices.\n \n - Climate Change Mitigation and Adaptation: Recognizing the threat of climate change, the policy focuses on reducing greenhouse gas emissions and adapting to the changing climate through initiatives like promoting renewable energy and disaster preparedness. \n \n - Pollution Control: The policy addresses air, water, and land pollution by promoting cleaner technologies, stricter emission norms, and proper waste management practices.\n \n - Strengthening Environmental Governance: The policy aims to improve environmental governance by enhancing public participation, promoting environmental awareness, and strengthening enforcement mechanisms.\n \n  The policy doesn't provide specific details about individual schemes. However, it lays the foundation for various government departments to develop and implement targeted programs that align with the overall environmental goals.\n \n  For instance, based on the policy's focus on water conservation, the government might introduce schemes promoting micro-irrigation techniques or rainwater harvesting.\n \n  Here are some resources for further exploration:\n \n - You can access the complete Tamil Nadu State Environment Policy 2017 document through the Tamil Nadu Department of Environment website or FAOLEX: faolex.fao.org ([PDF document]).\n \n - The India Environment Portal also provides a summary of the policy India Environment Portal: indiaenvironmentportal.org.in.",
  epred:"The Environment Protection and Renewable Energy Development Fund (EPRED Fund) is a key initiative of the Tamil Nadu government that supports projects aimed at environmental protection and promoting renewable energy sources. Here's a breakdown of the scheme:\n \n Objectives:\n \n Environmental Protection: The fund supports projects that address environmental degradation and promote sustainable practices. This could include initiatives like:\n \n - Pollution control measures for air, water, and land.\n \n - Conservation of natural resources like forests and water bodies.\n \n - Waste management and recycling programs.\n \n - Biodiversity conservation efforts.\n \n  Renewable Energy Development: The fund encourages the adoption of clean energy sources to reduce dependence on fossil fuels and combat climate change. This might involve supporting projects for:\n \n - Installation of solar power panels.\n \n - Development of wind farms.\n \n - Research and development in renewable energy technologies.\n \n - Promoting energy efficiency measures.\n \n  Project Scope:\n \n  The EPRED Fund caters to two main types of activities:\n \n - Promotional Activities: These initiatives focus on raising awareness, capacity building, and promoting public participation in environmental protection and renewable energy adoption. This could include workshops, training programs, and awareness campaigns.\n \n - Project-Based Activities: The fund provides financial assistance for specific projects that directly contribute to environmental protection and renewable energy development. These projects can be undertaken by government agencies, local bodies, NGOs, or even private institutions.\n \n  Funding and  Approval Process:\n \n  Details on the current allocation and budgetary aspects of the EPRED Fund might be subject to change.  However, in the past, the fund had a total corpus of Rs. 365 crores.\n \n  An Empowered Committee headed by the Chief Secretary to the Government oversees the  EPRED Fund's operationalization and approves proposals.  Proposals are typically submitted by implementing departments or organizations  aligned with the fund's objectives.\n \n  Overall, the EPRED Fund plays a significant role in supporting Tamil Nadu's  environmental and clean energy goals.\n \n  For further information, you can visit the Tamil Nadu Environment Department's website  on environmental protection and renewable energy development (https://www.environment.tn.gov.in/epred). While the website  might not provide details on the current funding specifics, it offers insights  into the fund's objectives and the types of projects it supports.",
  nlcp:"The National Lake Conservation Programme (NLCP) is a centrally sponsored scheme launched by the Ministry of Environment, Forest and Climate Change (MoEF&CC) of the Government of India. It specifically targets the restoration and conservation of polluted and degraded lakes in urban and semi-urban areas.n \n Objectives of NLCP:\n \n - Improve water quality: The program aims to significantly improve the water quality of targeted lakes through various measures to address pollution sources.\n \n - Restore lake ecology: NLCP focuses on reviving the ecological health of lakes by controlling invasive weeds, promoting native vegetation, and addressing issues affecting fish and other aquatic life.\n \n - Sustainable lake management: The program encourages practices for long-term, sustainable management of lakes, involving community participation and proper lakefront development.\n \n  Key features of NLCP:\n \n - Funding: NLCP operates on a cost-sharing basis between the central government and the respective state governments. Currently, the central government contributes 70% of the project cost, while the state government bears the remaining 30%.\n \n - Project identification: The MoEF&CC identifies potential lakes for conservation in consultation with state governments. States then submit proposals for consideration and approval.\n \n - Project components: NLCP projects typically involve a combination of activities such as:\n \n Current status of NLCP:\n \n - The NLCP was originally launched in 2001.\n \n - In 2013, it was merged with the National Wetlands Conservation Programme (NWCP) into a new scheme called the National Plan for Conservation of Aquatic Eco-systems (NPCA).\n \n - However, the core objectives of lake conservation remain the same under the NPCA.\n \n  Impact of NLCP:\n \n  The NLCP has played a role in improving the condition of many lakes in India. However, there are also challenges in ensuring proper implementation, securing long-term sustainability, and addressing the vast number of lakes requiring conservation efforts.\n \n  Here are some resources for further information on the NLCP:\n \n - PIB (Press Information Bureau) Government of India: National Lake Conservation Plan - PIB: https://pib.gov.in/newsite/erelcontent.aspx?relid=16404",
  tbgp:"The Tamil Nadu Biodiversity Conservation and Greening Project (TBGP) was an ambitious initiative launched by the Tamil Nadu Forest Department in collaboration with the Japan International Cooperation Agency (JICA). It aimed to strengthen biodiversity conservation efforts across the entire state of Tamil Nadu, running from 2011-12 to 2018-19.\n \n Key Objectives of TBGP:\n \n - Habitat Improvement: The project focused on improving the habitats of various flora and fauna within protected areas like National Parks and Wildlife Sanctuaries. This involved activities like controlling invasive species, promoting native vegetation growth, and creating corridors for wildlife movement.\n \n - Afforestation: TBGP aimed to increase green cover outside forest areas by encouraging tree plantation on private lands. This strategy aimed to improve biodiversity by creating new habitats for wildlife and enhancing ecological connectivity across the landscape.\n \n - Institutional Capacity Development: The project also emphasized strengthening the capacity of forest departments and other stakeholders involved in biodiversity conservation. This included training programs, workshops, and knowledge sharing initiatives.\n \n  Components of TBGP:\n \n - Focus on Protected Areas: The project prioritized nine Protected Areas and ten Elephant Reserves spread across Tamil Nadu. Activities within these areas aimed to improve habitat quality for resident wildlife populations.\n \n - Community Participation: TBGP actively involved local communities in conservation efforts. This fostered a sense of ownership and ensured the long-term sustainability of the project's outcomes.\n \n - Tree Plantation on Private Lands: The project collaborated with farmers to plant suitable tree species on their lands. This not only increased green cover but also provided additional income sources for farmers.\n \n  Outcomes and Significance:\n \n - Improved Biodiversity: TBGP's habitat improvement initiatives likely contributed to a rise in biodiversity within protected areas.\n \n - Increased Forest Cover: The tree plantation drives on private lands helped to increase green cover in the state.\n \n - Enhanced Capacity Building: Training programs likely empowered forest departments and stakeholders with improved knowledge and skills for effective conservation management.\n \n  Current Status:\n \n - While the initial TBGP project concluded in 2019, the Tamil Nadu Forest Department might  be undertaking new initiatives aimed at similar goals. You can  check the department's website for any updates on ongoing projects  (https://www.forests.tn.gov.in/).",


};



const generateResponse = (chatElement, userInput) => {
  const messageElement = chatElement.querySelector("p");
  const response = predefinedResponses[userInput.toLowerCase()];
  if (response) {
    messageElement.innerHTML = response; // Allow for HTML content (including links)

    // Find the link element (if present) and attach the event listener
    const linkElement = messageElement.querySelector("a");
    if (linkElement) {
      linkElement.addEventListener("click", () => {
        window.open(linkElement.href, "_blank"); // Open link in new tab
      });
    }
  } else {
    messageElement.textContent =
      "I'm sorry, I didn't understand that. Can you please rephrase?"; // Handle unknown input
  }
};



const handleChat = () => {
  userMessage = chatInput.value.trim();
  if (!userMessage) return;

  chatInput.value = "";
  chatInput.style.height = `${inputInitHeight}px`;

  chatbox.appendChild(createChatLi(userMessage, "outgoing"));
  chatbox.scrollTo(0, chatbox.scrollHeight);

  setTimeout(() => {
    const incomingChatLi = createChatLi("Thinking...", "incoming");
    chatbox.appendChild(incomingChatLi);
    chatbox.scrollTo(0, chatbox.scrollHeight);

    generateResponse(incomingChatLi, userMessage); // Pass user's input message to generateResponse
  }, 600);
};

chatInput.addEventListener("input", () => {
  // Adjust the height of the input textarea based on its content
  chatInput.style.height = `${inputInitHeight}px`;
  chatInput.style.height = `${chatInput.scrollHeight}px`;
});

chatInput.addEventListener("keydown", (e) => {
  // If Enter key is pressed without Shift key and the window
  // width is greater than 800px, handle the chat
  if (e.key === "Enter" && !e.shiftKey && window.innerWidth > 800) {
    e.preventDefault();
    handleChat();
  }
});

sendChatBtn.addEventListener("click", handleChat);
closeBtn.addEventListener("click", () => document.body.classList.remove("show-chatbot"));
chatbotToggler.addEventListener("click", () => document.body.classList.toggle("show-chatbot"));
